[package]
name = "asroute"
description = "CLI to interpret traceroute -a output to show names of Autonomous Systems traversed"
version = "0.1.0"
authors = ["Steven Pack <steven.pack.code@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
cymrust = "0.3.4"
clap = "3.0.0-beta.2"